// <auto-generated />
using ExamenFInal.Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamenFInal.Migrations
{
    [DbContext(typeof(Conn))]
    [Migration("20211113184916_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamenFInal.Models.BodegaModel", b =>
                {
                    b.Property<int>("IdBodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("NombreBodega")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<int>("cantidadProducto")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.HasKey("IdBodega");

                    b.HasIndex("IdProducto");

                    b.ToTable("Bodega");
                });

            modelBuilder.Entity("ExamenFInal.Models.ProductoModel", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoProducto")
                        .HasColumnType("varchar(3)");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float(35)");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("ExamenFInal.Models.ProveedoresModel", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoProveedor")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("IdProveedor");

                    b.ToTable("proveedoro");
                });

            modelBuilder.Entity("ExamenFInal.Models.BodegaModel", b =>
                {
                    b.HasOne("ExamenFInal.Models.ProductoModel", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ExamenFInal.Models.ProductoModel", b =>
                {
                    b.HasOne("ExamenFInal.Models.ProveedoresModel", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
